build:
	@go build -C ./cmd/title/ -o ~/.local/bin/title
	@echo "title.go successfully built\n\tCLI: Title"

	@go build -C ./cmd/url/ -o ~/.local/bin/url
	@echo "url.go successfully built\n\tCLI: url"

test:
	go test ./...
